version: '3.8'
services:
  neo4j:
    image: neo4j:5.15.0
    container_name: ripple-neo4j
    ports:
      - "7474:7474" # HTTP (Browser)
      - "7687:7687" # Bolt (Application)
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data:/data
